// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateStoreInput struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

type CreateUserInput struct {
	Email           string `json:"email"`
	Name            string `json:"name"`
	Pasword         string `json:"pasword"`
	PosswordConfirm string `json:"posswordConfirm"`
}

type LoginUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Session struct {
	Token string `json:"token"`
}
